title: Anush Manglani
url: "https://anushmanglani.github.io"
baseurl: "https://anushmanglani.github.io"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://anushmanglani.github.io"
footer_text: "Ansuh Manglani<br><br>"

sass:
    style: compressed
    sass_dir: _sass

nav:
# - name: "About"
#   link: "/"
 - name: "Portfolio"
   link: "/portfolio/"
 - name: "Google Scholar"
   link: ""
 - name: "Blog"
   link: ""
 - name: "CV"
   link: ""

