title: Aman Agarwal
url: "https://amanbasu.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/amanbasu"
footer_text: "Aman Agarwal <br><br>"

sass:
    style: compressed
    sass_dir: _sass

nav:
# - name: "About"
#   link: "/"
 - name: "Portfolio"
   link: "/portfolio/"
 - name: "Google Scholar"
   link: "https://scholar.google.com/citations?user=pbuqtFQAAAAJ&hl=en"
# - name: "LinkedIn"
#   link: "https://www.linkedin.com/in/theabecedarian/"
 - name: "Blog"
   link: "blog"
 - name: "Resume"
   link: "resume.pdf"
